export const JugadorData = [
    {'numeroCamiseta':500,'nombreCamiseta':'Jeff','nombreCompletoJugador':'Jefferson Montero','poderEspecialDos':'lateral','fechaIngresoEquipo':'2018-08-08','goles':'10','equipoFutbolId':'1','img_jug': 'http://www.futbolizados.com/wp-content/uploads/2015/03/jefferson_montero_ecuador.jpg'},
    {'numeroCamiseta':10,'nombreCamiseta':'Cristiano','nombreCompletoJugador':'Cristiano Ronaldo','poderEspecialDos':'delantero','fechaIngresoEquipo':'2016-08-08','goles':'5','equipoFutbolId':'1','img_jug': 'https://www.infobae.com/new-resizer/DUR37cFBjClCwR0KyX2Yu0O6IOA=/600x0/filters:quality(100)/s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2018/06/20093122/cristiano-ronaldo-barba-1920-1.jpg'},
    {'numeroCamiseta':20,'nombreCamiseta':'Leo','nombreCompletoJugador':'Leo Messi','poderEspecialDos':'10','fechaIngresoEquipo':'2014-08-08','goles':'8','equipoFutbolId':'2','img_jug': 'http://e.rpp-noticias.io/xlarge/2017/12/25/541872jugadores-2jpg.jpg'},
    {'numeroCamiseta':40,'nombreCamiseta':'Neymar','nombreCompletoJugador':'Neymar Junior','poderEspecialDos':'caerse','fechaIngresoEquipo':'2010-08-08','goles':'10','equipoFutbolId':'2','img_jug': 'http://www.regiodeporte.com/wp-content/uploads/2017/08/image-2017-08-04-754x424.jpg'},
    {'numeroCamiseta':6,'nombreCamiseta':'Hazard','nombreCompletoJugador':'Eden Hazard','poderEspecialDos':'delantero','fechaIngresoEquipo':'2008-08-08','goles':'20','equipoFutbolId':'3','img_jug': 'https://estaticos.sport.es/resources/jpg/4/5/hazard-tono-jocoso-aseguro-que-premio-mejor-jugador-del-mundial-tendrian-que-dar-1531588822154.jpg'},
    {'numeroCamiseta':12,'nombreCamiseta':'Kevin','nombreCompletoJugador':'Kevin de Bruyne','poderEspecialDos':'eliminar enemigos','fechaIngresoEquipo':'2006-08-08','goles':'5','equipoFutbolId':'3','img_jug': 'https://s.hs-data.com/bilder/spieler/gross/142263.jpg'},
    {'numeroCamiseta':500,'nombreCamiseta':'Maximo','nombreCompletoJugador':'Maximo Banguera','poderEspecialDos':'arquero','fechaIngresoEquipo':'2008-08-08','goles':'10','equipoFutbolId':'4','img_jug': 'http://sfcdn.studiofutbol1.netdna-cdn.com/wp-content/uploads/2017/09/Bangue.jpg'},
    {'numeroCamiseta':10,'nombreCamiseta':'Oyola','nombreCompletoJugador':'Matias Oyola','poderEspecialDos':'hacha','fechaIngresoEquipo':'2007-08-08','goles':'5','equipoFutbolId':'5','img_jug': 'https://www.eltiempo.com.ec/media/k2/items/cache/d63019941d84c6d37f0de8cc7bd64f9b_M.jpg'},
];